version: 0.2
   
phases:
  install:
    runtime-versions:
      ruby: 2.6    
    commands:
      - gem install jekyll bundler
      - bundle install
  build:
    commands:
      - jekyll build
artifacts:
  files:
      - '**/*'
  base-directory: '_site'
      

      